# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/dockerfile'
        tags: |
          $(gamics:latest)
    - script: 
      displayName: List the docker images
          docker images
    - job: BuildAndRun
       displayName: Build and Run Docker Image
       pool:
       vmImage: ubuntu-latest

       variables:
        imageName: 'gamics'
        tag: 'latest'
        containerName: 'gamics-container'
        containerPort: '3000'    # Change this to match your app's internal port
        hostPort: '8080'         # Port exposed on the host machine

  steps:
  - task: Docker@2
    displayName: Build Docker Image
    inputs:
      command: build
      dockerfile: '$(Build.SourcesDirectory)/dockerfile'
      tags: |
        $(imageName):$(tag)

  - script: |
      echo "Listing Docker images..."
      docker images
    displayName: List Docker Images

  - script: |
      echo "Running Docker container..."
      docker run -d -p $(hostPort):$(containerPort) --name $(containerName) $(imageName):$(tag)
    displayName: Run Docker Container

  - script: |
      echo "Showing running containers..."
      docker ps
    displayName: List Running Containers

  - script: |
      echo "Testing app endpoint..."
      curl http://localhost:$(hostPort) || echo "App not reachable yet"
    displayName: Test App Endpoint
      

