# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/dockerfile'
        tags: |
          $(gamics:latest)
    - script: 
      displayName: List the docker images
          docker images ls
    - script:
        docker build -t gamics:latest . -f dockerfile
      displayName: build container image
    - script: 
         docker run -d gamics:latest
      displayName: Run the app
    - script: 
        docker ps
      displayName: List the running image
    - script: |
        echo "Running container and exposing port 8080..."
        docker run -d -p 8080:80 --name gamics-container gamics:latest
      displayName: Run Docker Container

    - script: |
        echo "Testing app endpoint..."
        curl http://localhost:8080 || echo "App not reachable yet"
      displayName: Test App Endpoint


 

